In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4806, 6246, 5024, 4114],
 [4806, 6246, 5024, 4497],
 [4806, 8969, 5024, 4001],
 [8856, 53, 8194, 7478, 6734],
 [8856, 53, 8194, 7478, 4034],
 [1852, 4806, 8948, 5024, 5556],
 [5908, 378, 3683, 7478]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4806 6246 5024 4114]
 [   0    0    0    0 4806 6246 5024 4497]
 [   0    0    0    0 4806 8969 5024 4001]
 [   0    0    0 8856   53 8194 7478 6734]
 [   0    0    0 8856   53 8194 7478 4034]
 [   0    0    0 1852 4806 8948 5024 5556]
 [   0    0    0    0 5908  378 3683 7478]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\code\Simple Rnn\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 397ms/step


array([[[-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.01131853, -0.0090325 , -0.03932214, -0.04252503,
         -0.04339069, -0.02305405,  0.02946379, -0.03597701,
          0.04627427, -0.02255472],
        [-0.0037875 ,  0.03183409,  0.00031158, -0.01745664,
         -0.00675297, -0.01893051, -0.01797957, -0.03393149,
          0.02542384,  0.02173425],
        [ 0.02763132, -0.04001974, -0.02555474,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4806, 6246, 5024, 4114], dtype=int32)

In [16]:
print(embedded_docs[0].shape)  # Should be (sequence_length,)


(8,)


In [17]:
import numpy as np
input_data = np.array([embedded_docs[0]])  # Ensure it's a 2D array
prediction1 = model.predict(input_data)
prediction1


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[[-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.00607262, -0.04623521,  0.00996842,  0.04843635,
         -0.01178656,  0.00620053,  0.02385558,  0.02001831,
         -0.01951708,  0.01987589],
        [-0.01131853, -0.0090325 , -0.03932214, -0.04252503,
         -0.04339069, -0.02305405,  0.02946379, -0.03597701,
          0.04627427, -0.02255472],
        [-0.0037875 ,  0.03183409,  0.00031158, -0.01745664,
         -0.00675297, -0.01893051, -0.01797957, -0.03393149,
          0.02542384,  0.02173425],
        [ 0.02763132, -0.04001974, -0.02555474,  0.0